//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CursoTurmaAluno
    {
        public int CursoTurmaAlunoID { get; set; }

        [Display(Name = "Sobre")]
        [Required(ErrorMessage = "O campo nome é Obrigatório")]
        public int ID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
