//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monitoria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.CursoTurmaAlunoes = new HashSet<CursoTurmaAluno>();
            this.Materias = new HashSet<Materia>();
        }

        [Key]
        public int ID { get; set; }


        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "Seu nome é Obrigatório")]
        public string Nome { get; set; }


        [Display(Name = "Sexo")]
        [Required(ErrorMessage = "Seu sexo é Obrigatório")]
        public string Sexo { get; set; }


        [Display(Name = "CPF")]
        [Required(ErrorMessage = "Seu CPF é Obrigatório")]
        public string CPF { get; set; }


        [DisplayName("Data de Nascimento")]
        [DataType(DataType.Date, ErrorMessage = "Uma data válida deve ser informada")]
        public string DataNascimento { get; set; }

        [Display(Name = "Perfil")]
        [Required(ErrorMessage = "Você é Aluno(A)" + "Ou é Professor(A)")]
        public string Perfil { get; set; }

        [Required(ErrorMessage = "Seu Email é Obrigatório")]
        [EmailAddress]
        [Display(Name = "Email")]
        [Index("EmailIndex", IsUnique = true)]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "O/A {0} deve ter no mínimo {2} caracteres.")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<CursoTurmaAluno> CursoTurmaAlunoes { get; set; }

        public virtual Curso Curso { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Materia> Materias { get; set; }

    }

}